# Generated by Django 2.0.3 on 2018-04-26 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20180426_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='useryou',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='useryou', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
