# Generated by Django 2.0.3 on 2018-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180429_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dataimg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
