# Generated by Django 2.0.3 on 2018-04-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_photo_dataimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imageuser',
            field=models.FileField(upload_to='imageinst', verbose_name='photouser'),
        ),
    ]
