# Generated by Django 2.0.3 on 2018-04-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180430_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='orphotoorvideo',
            field=models.BooleanField(default=True),
        ),
    ]
