# Generated by Django 2.0.3 on 2018-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180430_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='userimage',
            new_name='user',
        ),
    ]
