# Generated by Django 2.0.3 on 2018-05-03 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_auto_20180430_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messagedo',
            field=models.ManyToManyField(blank=True, related_name='messagedo', to=settings.AUTH_USER_MODEL),
        ),
    ]
