# Generated by Django 2.0.3 on 2018-05-03 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_userprofile_messagedo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allmessagesstory',
            field=models.ManyToManyField(blank=True, related_name='allmessagesstory', to=settings.AUTH_USER_MODEL),
        ),
    ]
