# Generated by Django 2.0.5 on 2018-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_allmessagesstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_online',
            field=models.BooleanField(default=False),
        ),
    ]
