# Generated by Django 2.0.5 on 2018-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180522_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
